### ISSUE TITLE
Just want to say thank you

### ISSUE THREAD

**Issue by gevera** [jumpwire-ai/elixirconf2022#2]
I've watched your presentation on youtube ElixirConf. I wanted to say that your project combines one of the two most loved tech stacks. Brilliant job of making them work together

**Comment by debussyman** [comment]
Thank you, glad you like it! This set up still makes me so happy when building web apps, I'm literally smiling while coding 😄. A lot of credit to @hexedpackets who figured out how to wire together LiveComponent and Svelte life-cycles. Would love to see what you are building on this stack sometime!
